# Generated by Django 5.2.5 on 2025-08-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_previous', models.FloatField()),
                ('departure_time', models.TimeField()),
                ('order', models.PositiveIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trains.train')),
            ],
            options={
                'ordering': ['train', 'order'],
            },
        ),
    ]
